spring:
  profiles:
    active: dev
  application:
    name: discodeit

logging:
  level:
    root: info

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, loggers"

info:
  app:
    name: Discodeit
    description: Discodeit Sprint Mission 7
    version: 1.7.0
  java:
    version: ${java.version}
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}