spring:
  application:
    name: discodeit

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

discodeit:
  repository:
    type: jcf #jcf | file
    file-directory: ".discodeit"